### ISSUE TITLE
Game freezes in villages

### ISSUE THREAD

**Issue by LRA10** [DracoAnimus/Coding#16]
The game freezes and stops responding when looking in the direction of guards and loot chests. Only happened on one of my computers. It might just be my laptop. It worked on my other computer.

**Comment by wildbill22** [comment]
If you have trouble with lag or the game freezing, trying going into the config (select Mods button and then select Draco Animus from list of Mods and  press Config) and in Mob Properties, set the "Maximum Guards per Village" to a lower number.

**Comment by LRA10** [comment]
Fixed. I think it was a problem with my computer.
