### ISSUE TITLE
Silver dragon mob doesn't move

### ISSUE THREAD

**Issue by VergilDarkSlayer** [DracoAnimus/Coding#23]
The silver dragon mob doesn'r move no matter what happens, even if you attack then, they don't even attack if you touch then

**Comment by wildbill22** [comment]
I'll fix this. Thanks for pointing this out. The egg you used for creating the silver dragon is not supposed to be available in the release build. I put it in there just for testing, and will remove it. The silver dragon is only for the player to become a dragon, it has no code that makes it work as an independent entity.
