### ISSUE TITLE
Skeleton dragon respawn

### ISSUE THREAD

**Issue by VergilDarkSlayer** [DracoAnimus/Coding#24]
when you die in skeletal dragon form you respawn as a silver dragon

**Comment by wildbill22** [comment]
Ya, that shouldn't happen, I'll see if I can fix this tonight.

**Comment by wildbill22** [comment]
This may not seem right. But it is based on what you initially spawned as, not what you were when you died. You have the option of spawning initially as either a human or the silver dragon, so depending on which you set in the configuration, you will spawn as those after you die.
