### ISSUE TITLE
Fireballs after kills

### ISSUE THREAD

**Issue by VergilDarkSlayer** [DracoAnimus/Coding#25]
You still get fireballs after killing mobs, I don't know if it still supposed to be there since we now have the staff

**Comment by wildbill22** [comment]
Ya, this private release you are testing was mainly for LRA to see some stuff. We still need to decide how the fireball and explosive fireball is going to work, now that there is the staff.

I will post this on the forum for discussion.

**Comment by VergilDarkSlayer** [comment]
*I have good internet now, just let me make a skype account*

2015-05-18 13:54 GMT-03:00 wildbill22 <notifications@github.com>:

**Comment by wildbill22** [comment]
0.2.2 check in
