### ISSUE TITLE
Odd Shifting with Tool Tips for staffs and Dragon Eggs

### ISSUE THREAD

**Issue by bosvan16** [DracoAnimus/Coding#26]
Problem: The tooltips on the staff and dragon egg items are a bit off the screen. Picture provided.
Replicable?: Yes.
If replicable, how can it be duplicated?: Opening up the Creative Tab for the mod in Creative mode and hovering over the fore mentioned items.

***NOTES***
- Only occurs with these items. My suggestion is making it multi-lined instead of double lined.
- Minecraft is fullscreen in that picture (F11 activates fullscreen).

***PICTURES***
![2015-05-18_20 44 29](https://cloud.githubusercontent.com/assets/12504866/7693657/c3a2c66a-fda2-11e4-8c77-8aa6e0b8418e.png)
![2015-05-18_20 44 31](https://cloud.githubusercontent.com/assets/12504866/7693658/c53398e2-fda2-11e4-856c-47f30b4ecc35.png)

**Comment by wildbill22** [comment]
Ok, I've fixed that by using shorting lines (I hope).
 
I'm adding more stuff right now, I'll release a new build when it is stable with this fix.
 
Thanks.

-----------
Bill Werth
 
Date: Mon, 18 May 2015 18:15:55 -0700

**Comment by wildbill22** [comment]
0.2.2 checkin.
