### ISSUE TITLE
Temporary hoard makes items disappear

### ISSUE THREAD

**Issue by LRA10** [DracoAnimus/Coding#6]
When you put any items except for the coin in they disappear.

**Comment by wildbill22** [comment]
I don't see how I can fix this. I think this is a problem with the Player Inventory, where it makes the assumption that a chest can accept any item it give it.

**Comment by wildbill22** [comment]
Can override Inventory/TileEntityChest isItemValidForSlot to fix this.

**Comment by wildbill22** [comment]
Hmm, for some reason the above function is never called. The mystery continues :)

**Comment by wildbill22** [comment]
Added a workaround, where other items are allowed in hoard, but a chat message is displayed when there are items other than gold coins in hoard.
