### ISSUE TITLE
Silver Dragon Head Bug

### ISSUE THREAD

**Issue by VergilDarkSlayer** [DracoAnimus/Coding#7]
The silver dragon head is not right positioned in the body its kinda floating

**Comment by HeartofDragons** [comment]
Not just the head. The wings and legs are also kinda detached. The parts aren't anchored properly. It also looks bizarre when it turns its everything to look at you. And there's a flashing texture thing on the wings, like it's got 2 different textures at the same time.
![2015-03-06_09 39 10](https://cloud.githubusercontent.com/assets/11338191/6529438/f37a5034-c3e5-11e4-9ce5-3be52b06b821.png)

**Comment by VergilDarkSlayer** [comment]
also in the version 0.0.8 the standing model floats in air and wings only appear when flying


![2015-03-11_18 44 35](https://cloud.githubusercontent.com/assets/6130487/6607589/c1b49a40-c81e-11e4-9a89-009d7108a897.png)
![Uploading 2015-03-11_18.44.38.png . . .]()

**Comment by wildbill22** [comment]
Thanks. Yes, we have an open invitation for a coder that can fix this stuff. The plan is to fix these eventually, but we didn't want to delay the release just for these visual bugs. Having no wings on the ground is on purpose, we will be adding a "folded wing" look eventually when the dragon is on the ground. If the wings were rendered on the ground, they would be all the way open, but the dragon on the ground isn't that wide, so I don't show them.

**Comment by wildbill22** [comment]
Assigned to LRA. Issue with animation appears to be either in the model or the animation created in MCA.
