### ISSUE TITLE
Floating Creeper Dragon

### ISSUE THREAD

**Issue by HeartofDragons** [DracoAnimus/Coding#8]
The creeper dragon seems to sometimes float about a block above the block it's "standing" on.
![2015-03-06_09 40 00](https://cloud.githubusercontent.com/assets/11338191/6529484/596743de-c3e6-11e4-8374-a8c8dd0dcf0c.png)

**Comment by LRA10** [comment]
It is supposed to do that. It doesn't fly yet so me made it hover a block above the ground.
