### ISSUE TITLE
Exploding Fireballs Bug

### ISSUE THREAD

**Issue by VergilDarkSlayer** [DracoAnimus/Coding#9]
The exploding fireball won't explode if hit an entity instead of the ground, sometimes(hitting a entity) it do a glitch explosion, the glitch explosion is basically that the terrain is damaged but when you interact with the blocks that exploded by or right clicking or placing a block on it, it will return to be a block

**Comment by wildbill22** [comment]
These are still a work in progress. When they are complete, I'll test that it explodes when it hits an entity.
